# Generated by Django 4.0.5 on 2022-06-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinceru_games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='registration_date',
            new_name='release_date',
        ),
    ]
